apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: invalid-secret
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: invalid-secret
        env:
        - name: notpresent
          valueFrom:
            secretKeyRef:
              name: notpresent
              key: notpresent
        command: ["exit 0"]
        resources:
          requests:
            memory: 1Gi
      restartPolicy: Never
status: {}
