apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: over-provisioned
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: polinux/stress
        imagePullPolicy: IfNotPresent
        name: over-provisioned
        command: ["stress", "--vm", "1", "--vm-bytes", "1G", "--vm-hang", "0"]
        resources:
          requests:
            memory: 2Gi
      restartPolicy: Never
status: {}
